export type Operation<Id, Value, Delta> =
	| {
			readonly type: "insert" | "remove";
			readonly value: Value;
			restoreWithId?: Id; // only meant for restoring removes; should not be generated by Builder!
			readonly parent: Id;
			readonly previousSibling?: Id;
	  }
	| {
			readonly type: "move";
			readonly tree: Id;
			readonly parent: Id;
			readonly previousSibling?: Id;
			readonly newParent: Id;
			readonly newPreviousSibling?: Id;
	  }
	| {
			readonly type: "change_value";
			readonly tree: Id;
			readonly delta: Delta;
	  };

export type Transaction<Id, Value, Delta> = ReadonlyArray<Operation<Id, Value, Delta>>;
